# -*- coding: utf-8 -*-
# tasks for  ansible-role-osquery
---
- name: Install/Setup osquery
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - osquery
    - xclip
  when: ansible_os_family == "Debian"

- name: Clone osquery config
  git:
    repo: https://github.com/gpakosz/.osquery
    dest: "{{item.dir}}/.osquery"
    version: "master"
  become: yes
  become_user: "{{item.user}}"
  with_items: "{{bossjones__osquery__path_to_osquery_config}}"

- name: Clone powerline fonts
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "{{item.dir}}/fonts"
    version: "master"
    depth: 1
  become: yes
  become_user: "{{item.user}}"
  with_items: "{{bossjones__osquery__path_to_osquery_config}}"

- name: bootstrap osquery.conf
  shell: |
            ln -s -f .osquery/.osquery.conf
            cp .osquery/.osquery.conf.local .
            chdir="{{item.dir}}"
  become: yes
  become_user: "{{item.user}}"
  with_items: "{{bossjones__osquery__path_to_osquery_config}}"

- name: Install powerline fonts
  shell: |
            # install
            cd fonts
            ./install.sh
            # clean-up a bit
            cd ..
            rm -rf fonts
            chdir="{{item.dir}}"
  become: yes
  become_user: "{{item.user}}"
  with_items: "{{bossjones__osquery__path_to_osquery_config}}"


